apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
spec:
  pipelineRef:
    name: build-and-push-pipeline
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: pipeline-pvc
  podTemplate:
    securityContext:
      fsGroup: 65532
    volumes:
    - name: docker-config
      secret:
        secretName: docker-credentials