apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
type: Opaque
data:
  username: YXl1c2htYW4tNw==
  password: Z2l0aHViX3BhdF8xMUE2SldEN0EwSGlDdTlHZENJR0VZX0R4SWNyU3paVE5iOVg2dVo2eFY5Rmt3aUhaN0JjUFhaVXBEanhCbkhURGdHRFkzWkRaSkdkOW82ZVVu
